# Use node.js + test on all supported versions
language: node_js
node_js:
  - '10'

install:
  - npm install

script:
  - npm run ci

# Update Coveralls
after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
